---
apiVersion: v2
name: urlaubsverwaltung
description: Helm Chart for the urlaubsverwaltung
type: application
version: "6.16.9"
appVersion: 5.29.2
keywords:
  - urlaub
home: https://github.com/urlaubsverwaltung/urlaubsverwaltung
sources:
  - https://github.com/urlaubsverwaltung/urlaubsverwaltung
maintainers:
  - name: Johannes Graf
    email: Johannes.Graf@focus-shift.de
  - name: Tobias Schneider
    email: Tobias.Schneider@focus-shift.de
dependencies:
  - name: postgresql
    version: 12.12.10
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
