version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    labels:
      - "type: dependencies"
      - "javascript"
    groups:
      rollup:
        patterns:
          - "@rollup/*"
          - "rollup"
          - "rollup-*"
      babel:
        patterns:
          - "@babel/*"
          - "babel-*"
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@eslint/*"
      jest:
        patterns:
          - "jest"
          - "jest-*"
      postcss:
        patterns:
          - "postcss"
          - "postcss-*"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "type: dependencies"
      - "java"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    labels:
      - "type: dependencies"
      - "github_actions"

  - package-ecosystem: "docker-compose"
    directories:
      - "/.examples/with-docker-compose"
    schedule:
      interval: "weekly"
