version: '3.9'
services:
  mariadb:
    image: mariadb:10.6.11
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'urlaubsverwaltung'
      MYSQL_USER: 'urlaubsverwaltung'
      MYSQL_PASSWORD: 'urlaubsverwaltung'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - '3308:3306'
    healthcheck:
      test: ["CMD", "bash", "-c", "/usr/bin/mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD --execute \"SHOW DATABASES;\""]
      interval: 3s
      timeout: 1s
      retries: 5

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - '1025:1025'
      - '8025:8025'

  keycloak:
    build: keycloak/
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8090
      KC_HTTP_RELATIVE_PATH: /auth
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      KC_HEALTH_ENABLED: 'true'
    ports:
      - '8090:8090'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/auth/health/ready"]
      interval: 30s
      timeout: 30s
      retries: 5

volumes:
  mariadb_data: {}

